# Generated by Django 3.2.4 on 2021-06-27 19:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0002_auto_20210614_0127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobs',
            old_name='industry',
            new_name='experience',
        ),
        migrations.AlterField(
            model_name='jobs',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 27, 19, 5, 7, 532924, tzinfo=utc)),
        ),
    ]
