# Generated by Django 3.2.4 on 2021-06-27 20:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0003_auto_20210627_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 27, 20, 0, 22, 237986, tzinfo=utc)),
        ),
    ]
