# Generated by Django 3.2.4 on 2021-06-27 20:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0004_alter_jobs_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 27, 20, 1, 45, 79418, tzinfo=utc)),
        ),
    ]
