# Generated by Django 3.2.4 on 2021-06-27 21:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0007_alter_jobs_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 27, 21, 52, 13, 533546, tzinfo=utc)),
        ),
    ]
