# Generated by Django 3.2.4 on 2021-06-30 10:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0008_alter_jobs_date_posted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='employer',
        ),
        migrations.AlterField(
            model_name='jobs',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 30, 10, 6, 8, 84746, tzinfo=utc)),
        ),
    ]
