# Generated by Django 3.2.4 on 2021-07-01 15:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Job', '0011_alter_jobs_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='employer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 1, 15, 56, 7, 785027, tzinfo=utc)),
        ),
    ]
