# Generated by Django 3.2.4 on 2021-12-05 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0003_jobs_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidates',
            name='cover',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
