# Generated by Django 3.2.4 on 2021-08-20 20:13

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Job', '0003_candidates'),
    ]

    operations = [
        migrations.CreateModel(
            name='new_company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('experience', models.CharField(blank=True, max_length=30, null=True)),
                ('summary', ckeditor.fields.RichTextField(blank=True, max_length=150, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, max_length=2000, null=True)),
                ('salary', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('location', models.CharField(blank=True, max_length=30, null=True)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.AlterField(
            model_name='candidates',
            name='company',
            field=models.ManyToManyField(blank=True, to='Job.new_company'),
        ),
    ]
