# Generated by Django 3.2.4 on 2021-08-20 20:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Job', '0004_auto_20210820_2013'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='new_company',
            new_name='Company',
        ),
    ]
