# Generated by Django 3.2.4 on 2021-08-20 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0007_alter_company_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
