# Generated by Django 3.2.4 on 2021-08-31 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0009_auto_20210829_1945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobs',
            old_name='author',
            new_name='company',
        ),
    ]
