# Generated by Django 3.2.4 on 2021-10-21 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0012_remove_jobs_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidates',
            name='company',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='company',
        ),
        migrations.AlterField(
            model_name='jobs',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
