# Generated by Django 3.2.4 on 2021-11-20 20:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0013_auto_20211021_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=1900),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobs',
            name='published',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='jobs',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
